In [3]:
import pandas as pd
import seaborn as sns
tips = sns.load_dataset('tips')

In [7]:
#label encoding 
sex_map = {'Male': 0, 'Female':1}
tips['sex_encoding'] = tips['sex'].map(sex_map)
print(tips[['sex', 'sex_encoding']].head())

      sex sex_encoding
0  Female            1
1    Male            0
2    Male            0
3    Male            0
4  Female            1

In [17]:
#one hot encoding 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
tips_df = pd.DataFrame(tips['sex'])
tips_encoded = encoder.fit_transform(tips_df['sex']).toarray()
tips_encoded

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [13]:
tips_onehot_encoded = pd.get_dummies(tips, columns=['sex'],prefix='sex', drop_first=True)

In [16]:
tips_onehot_encoded[['sex_Female']].head()

   sex_Female
0        True
1       False
2       False
3       False
4        True

In [19]:
df = pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,180,320]
})

In [20]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [24]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [25]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [27]:
df['city_encoded'] = df['city'].map(mean_price)

In [28]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0