In [1]:
import pandas as pd
import seaborn as sns
tips = sns.load_dataset('tips')

In [7]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
 7   bill_time   244 non-null    category
dtypes: category(5), float64(2), int64(1)
memory usage: 7.7 KB

In [9]:
mean_bill_12 = tips['total_bill'].mean()
mean_bill_12

np.float64(19.78594262295082)

In [2]:
mean_bill = tips.groupby('time')['total_bill'].mean()

/var/folders/nj/w5bt58qx70g7bt951nhy07580000gn/T/ipykernel_89648/3722237297.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_bill = tips.groupby('time')['total_bill'].mean()

In [3]:
mean_bill

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [ ]:
# making a new column in out dataset to represent new data i.e. the mean of the total bill for each time of day 
tips['bill_time'] = tips['time'].map(mean_bill)

In [5]:
tips

     total_bill   tip     sex smoker   day    time  size  bill_time
0         16.99  1.01  Female     No   Sun  Dinner     2  20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3  20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3  20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2  20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4  20.797159
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2  20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2  20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2  20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2  20.797159

[244 rows x 8 columns]

In [6]:
tips[tips['time']=='Lunch'].head()

    total_bill   tip   sex smoker   day   time  size  bill_time
77       27.20  4.00  Male     No  Thur  Lunch     4  17.168676
78       22.76  3.00  Male     No  Thur  Lunch     2  17.168676
79       17.29  2.71  Male     No  Thur  Lunch     2  17.168676
80       19.44  3.00  Male    Yes  Thur  Lunch     2  17.168676
81       16.66  3.40  Male     No  Thur  Lunch     2  17.168676